_target_: src.models_bench.modules.deepvo.DeepVO
image_shape: [ 600, 180 ]
sequence_len: 7
hidden_size: 1000
pretrained_cnn_path: ${data_dir}/checkpoints/flownets_bn_EPE2.459.pth.tar
pose_decoder:
  _target_: src.models_bench.modules.deepvo.layers.VOPoseConstrainQuaternionDecoder
  input_dim: 1000