defaults:
  - torch_model: deepvo_original.yaml

_target_: src.models_bench.DeepVOModel

lr: 0.0004
betas: [ 0.99, 0.999 ]
epoch_count_optimizer: 10

odometry_loss:
  need: yes
  is_trainable: no
  coef_coord: 1.0
  coef_angle: 50.0

geometric_loss:
  need: yes
  is_trainable: no
  coef_coord: 1.0
  coef_angle: 50.0